### ISSUE TITLE
Lorem

### ISSUE THREAD

**Issue by ozodbekorolov23** [LazizbekTursunov/NewWork#1]
https://github.com/LazizbekTursunov/NewWork/blob/2146014e91aec5fb30c5e7d13216d6833e6c94dd/index.html#L9
loremni a gami  p gami o'ra.

**Comment by LazizbekTursunov** [comment]
Bo'ldi okaxon nima desangiz shu😁

**Comment by LazizbekTursunov** [comment]
Bo'ldi gap yo'q
